testMaze:
	python2.7 pacman.py --layout testMaze --pacman GoWestAgent
tinyMaze:
	python2.7 pacman.py --layout tinyMaze --pacman GoWestAgent
	
testSearchAgent:
	python2.7 pacman.py -l tinyMaze -p SearchAgent -a fn=tinyMazeSearch
	